// Minimal activity row for listing/filtering (SQLite is a read snapshot of Postgres).
#[allow(dead_code)]
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ActivitiesRow {
    pub activity_id: String,
    pub title: String,
    pub description: Option<String>,
    pub activity_type: String,
    pub privacy_level: String,
    pub status: String,
    pub scheduled_at: String,
    pub duration_minutes: Option<i64>,
    pub joinable_at_free: Option<String>,
    pub max_participants: i64,
    pub current_participants_count: i64,
    pub waitlist_count: i64,
    pub city: Option<String>,
    pub distance_km: Option<f64>,
    pub latitude: Option<f64>,
    pub longitude: Option<f64>,
    pub location: Option<String>,
    pub organizer: String,
    pub tags: Option<String>,
    pub category: Option<String>,
    pub my_role: Option<String>,
    pub my_participation_status: Option<String>,
    pub my_attendance_status: Option<String>,
    pub am_on_waitlist: i64,
    pub my_waitlist_position: Option<i64>,
    pub main_photo_asset_id: Option<String>,
    pub is_joined: i64,
    pub can_manage_activity: i64,
    pub can_manage_attendance: i64,
}
