#[derive(Debug, Clone, sqlx::FromRow)]
pub struct PromotionUnitRow {
    pub promotion_unit_id: String,
    pub placement: String,
    pub promo_group: String,
    pub locale: String,
    pub priority: i64,
    pub weight: i64,
    pub is_active: i64,
    pub starts_at: Option<String>,
    pub ends_at: Option<String>,
    pub title: Option<String>,
    pub body: Option<String>,
    pub emoji: Option<String>,
    pub layout_kind: Option<String>,
    pub background_color: Option<String>,
    pub background_gradient: Option<String>,
    pub media_kind: Option<String>,
    pub media_asset_id: Option<String>,
    pub poster_asset_id: Option<String>,
    pub video_autoplay: i64,
    pub video_muted: i64,
    pub video_loop: i64,
    pub video_controls: i64,
    pub actions_json: Option<String>,
    pub created_at: String,
    pub updated_at: Option<String>,
}
